test_that("exported public APIs support numeric, matrix, zoo, and xts inputs as documented", {
  numeric_sim <- c(1, 2, 3, 4)
  numeric_obs <- c(1, 2, 2, 4)
  matrix_sim <- cbind(a = c(1, 2, 3), b = c(2, 3, 4))
  matrix_obs <- cbind(a = c(1, 2, 2), b = c(2, 2, 3))

  expect_s3_class(gof(numeric_sim, numeric_obs, methods = "NSE"), "hydro_metrics")
  expect_s3_class(ggof(matrix_sim, matrix_obs, methods = c("NSE", "rmse")), "hydro_metrics_batch")
  expect_type(NSE(numeric_sim, numeric_obs), "double")
  expect_type(PBIAS(numeric_sim, numeric_obs), "double")
  expect_type(R2(numeric_sim, numeric_obs), "double")
  expect_type(NRMSE(numeric_sim, numeric_obs, norm = "mean"), "double")
  expect_true(is.numeric(NSE(matrix_sim, matrix_obs)))
  expect_true(is.numeric(PBIAS(matrix_sim, matrix_obs)))
  expect_true(is.numeric(R2(matrix_sim, matrix_obs)))
  expect_true(is.numeric(NRMSE(matrix_sim, matrix_obs, norm = "mean")))

  skip_if_not_installed("zoo")
  zoo_idx <- as.Date("2021-01-01") + 0:3
  zoo_sim <- zoo::zoo(c(1, 2, 3, 4), order.by = zoo_idx)
  zoo_obs <- zoo::zoo(c(1, 2, 2, 4), order.by = zoo_idx)
  apfb_idx <- as.Date(c("2020-01-01", "2020-06-01", "2021-01-01", "2021-06-01"))
  apfb_sim <- zoo::zoo(c(12, 18, 33, 35), order.by = apfb_idx)
  apfb_obs <- zoo::zoo(c(10, 20, 30, 40), order.by = apfb_idx)

  expect_s3_class(gof(zoo_sim, zoo_obs, methods = c("NSE", "rmse")), "hydro_metrics")
  expect_s3_class(ggof(zoo_sim, zoo_obs, methods = c("NSE", "rmse")), "hydro_metrics_batch")
  expect_type(NSE(zoo_sim, zoo_obs), "double")
  expect_type(PBIAS(zoo_sim, zoo_obs), "double")
  expect_type(R2(zoo_sim, zoo_obs), "double")
  expect_type(NRMSE(zoo_sim, zoo_obs, norm = "mean"), "double")
  expect_s3_class(APFB(apfb_sim, apfb_obs), "hydro_metric_scalar")

  skip_if_not_installed("xts")
  xts_sim <- xts::xts(c(1, 2, 3, 4), order.by = zoo_idx)
  xts_obs <- xts::xts(c(1, 2, 2, 4), order.by = zoo_idx)
  xts_apfb_sim <- xts::xts(c(12, 18, 33, 35), order.by = apfb_idx)
  xts_apfb_obs <- xts::xts(c(10, 20, 30, 40), order.by = apfb_idx)

  expect_s3_class(gof(xts_sim, xts_obs, methods = c("NSE", "rmse")), "hydro_metrics")
  expect_s3_class(ggof(xts_sim, xts_obs, methods = c("NSE", "rmse")), "hydro_metrics_batch")
  expect_type(NSE(xts_sim, xts_obs), "double")
  expect_type(PBIAS(xts_sim, xts_obs), "double")
  expect_type(R2(xts_sim, xts_obs), "double")
  expect_type(NRMSE(xts_sim, xts_obs, norm = "mean"), "double")
  expect_s3_class(APFB(xts_apfb_sim, xts_apfb_obs), "hydro_metric_scalar")
})
