run_behavior_matrix_check <- function(context) {
  matrix_path <- file.path(context$notes_dir, "edge_case_behavior_matrix.csv")

  code <- paste(
    "library(hydroMetrics)",
    "targets <- c('NSE', 'KGE', 'RMSE', 'PBIAS', 'R2', 'NRMSE', 'gof', 'preproc')",
    "exports <- getNamespaceExports('hydroMetrics')",
    "ns <- asNamespace('hydroMetrics')",
    "run_case <- function(fun_name, edge_case, sim, obs, input_class, notes = '') {",
    "  if (!(fun_name %in% exports)) {",
    "    return(data.frame(",
    "      function_name = fun_name,",
    "      edge_case = edge_case,",
    "      input_class = input_class,",
    "      behavior = 'not_exported',",
    "      return_value_or_condition = 'clean-session export missing',",
    "      deterministic = TRUE,",
    "      documented = FALSE,",
    "      notes = if (nzchar(notes)) notes else 'Current snapshot does not export this public wrapper.',",
    "      stringsAsFactors = FALSE",
    "    ))",
    "  }",
    "  fn <- get(fun_name, envir = ns, inherits = FALSE)",
    "  invoke <- function() fn(sim = sim, obs = obs)",
    "  call_once <- function() {",
    "    warnings <- character()",
    "    result <- withCallingHandlers(",
    "      tryCatch(list(ok = TRUE, value = invoke()), error = function(e) list(ok = FALSE, value = conditionMessage(e))),",
    "      warning = function(w) {",
    "        warnings <<- c(warnings, conditionMessage(w))",
    "        invokeRestart('muffleWarning')",
    "      }",
    "    )",
    "    list(result = result, warnings = warnings)",
    "  }",
    "  first <- call_once()",
    "  second <- call_once()",
    "  deterministic <- identical(first, second)",
    "  outcome <- if (isTRUE(first$result$ok)) 'returned' else 'condition'",
    "  rendered <- if (isTRUE(first$result$ok)) {",
    "    paste(capture.output(str(first$result$value)), collapse = ' ')",
    "  } else {",
    "    first$result$value",
    "  }",
    "  if (length(first$warnings) > 0L) rendered <- paste(rendered, paste('warnings:', paste(first$warnings, collapse = ' | ')), sep = '; ')",
    "  data.frame(",
    "    function_name = fun_name,",
    "    edge_case = edge_case,",
    "    input_class = input_class,",
    "    behavior = outcome,",
    "    return_value_or_condition = rendered,",
    "    deterministic = deterministic,",
    "    documented = fun_name %in% c('gof', 'ggof'),",
    "    notes = notes,",
    "    stringsAsFactors = FALSE",
    "  )",
    "}",
    "cases <- list(",
    "  list(name = 'perfect fit', sim = c(1, 2, 3, 4, 5), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'biased fit', sim = c(2, 3, 4, 5, 6), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'noisy fit', sim = c(1, 2.1, 2.5, 4.8, 4.7), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'NA pairs', sim = c(1, NA, 3, 4, 5), obs = c(1, 2, NA, 4, 5), class = 'numeric'),",
    "  list(name = 'constant observed', sim = c(1, 2, 3, 4, 5), obs = c(3, 3, 3, 3, 3), class = 'numeric'),",
    "  list(name = 'constant simulated', sim = c(3, 3, 3, 3, 3), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'zero-heavy flow series', sim = c(0, 0, 1, 0, 2), obs = c(0, 1, 0, 0, 2), class = 'numeric'),",
    "  list(name = 'length mismatch', sim = c(1, 2, 3, 4), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'Inf / NaN contamination', sim = c(1, 2, Inf, NaN, 5), obs = c(1, 2, 3, 4, 5), class = 'numeric'),",
    "  list(name = 'matrix / multiseries input', sim = cbind(a = c(1, 2, 3), b = c(2, 3, 4)), obs = cbind(a = c(1, 2, 2.5), b = c(2, 2.8, 4)), class = 'matrix')",
    ")",
    "if (requireNamespace('zoo', quietly = TRUE)) {",
    "  idx <- as.Date('2020-01-01') + 0:4",
    "  cases[['indexed zoo input']] <- list(name = 'indexed zoo input', sim = zoo::zoo(c(1, 2, 3, 4, 5), idx), obs = zoo::zoo(c(1, 2, 3, 4, 5), idx), class = 'zoo')",
    "} else {",
    "  cases[['indexed zoo input']] <- list(name = 'indexed zoo input', sim = NULL, obs = NULL, class = 'zoo-missing')",
    "}",
    "if (requireNamespace('xts', quietly = TRUE)) {",
    "  idx <- as.Date('2020-01-01') + 0:4",
    "  cases[['indexed xts input']] <- list(name = 'indexed xts input', sim = xts::xts(c(1, 2, 3, 4, 5), idx), obs = xts::xts(c(1, 2, 3, 4, 5), idx), class = 'xts')",
    "} else {",
    "  cases[['indexed xts input']] <- list(name = 'indexed xts input', sim = NULL, obs = NULL, class = 'xts-missing')",
    "}",
    "rows <- list()",
    "for (fun_name in targets) {",
    "  for (case_item in cases) {",
    "    if (grepl('-missing$', case_item$class)) {",
    "      rows[[length(rows) + 1L]] <- data.frame(",
    "        function_name = fun_name,",
    "        edge_case = case_item$name,",
    "        input_class = sub('-missing$', '', case_item$class),",
    "        behavior = 'condition',",
    "        return_value_or_condition = paste(sub('-missing$', '', case_item$class), 'package not installed in current environment'),",
    "        deterministic = TRUE,",
    "        documented = FALSE,",
    "        notes = 'Environment lacks optional time-series dependency required for this input class.',",
    "        stringsAsFactors = FALSE",
    "      )",
    "      next",
    "    }",
    "    rows[[length(rows) + 1L]] <- run_case(fun_name, case_item$name, case_item$sim, case_item$obs, case_item$class)",
    "  }",
    "}",
    "matrix_df <- do.call(rbind, rows)",
    sprintf("utils::write.csv(matrix_df, %s, row.names = FALSE, na = '')", shQuote(rr_normalize_file(matrix_path))),
    sep = "\n"
  )

  run <- rr_run_r_code(code, wd = context$root)
  behavior_df <- rr_load_csv_if_exists(matrix_path)
  missing_exports <- if (nrow(behavior_df) > 0L) unique(behavior_df$function_name[behavior_df$behavior == "not_exported"]) else c("NSE", "KGE", "RMSE", "PBIAS", "R2", "NRMSE", "preproc")

  rr_result(
    stage = "behavioral correctness matrix",
    status = if (length(missing_exports) == 0L && identical(run$status, 0L)) "PASS" else "FAIL",
    summary = if (length(missing_exports) == 0L && identical(run$status, 0L)) {
      "Edge-case matrix executed for all representative public functions."
    } else {
      sprintf(
        "Edge-case matrix captured current runtime behavior, but the following representative functions are not exported: %s.",
        paste(missing_exports, collapse = ", ")
      )
    },
    fatal = FALSE,
    artifacts = matrix_path,
    details = list(exit_status = run$status)
  )
}
